'use client';

import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import { loginEndpoint, skyvaultApi } from 'lib/services/endpoint';
import { useRouter } from 'next/router';

export default function Home() {
  return (
    <>
      <Head>
        <title>SkyVault</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/cloudversify.svg" />
      </Head>
      <main>Sign In to upload Files</main>
    </>
  );
}
