'use client';

import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import { loginEndpoint, skyvaultApi } from 'lib/services/endpoint';
import { useRouter } from 'next/router';
import { Button } from '@tanchohang/langtang-rcl';
import Link from 'next/link';
import { Auth } from './_app';
import { useSession } from 'next-auth/react';

export default function Home() {
  const session = useSession();
  return (
    <>
      <Head>
        <title>SkyVault</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/cloudversify.svg" />
      </Head>
      <main className="flex justify-center items-center h-[80vh]">
        {!session.data?.user && (
          <div>
            <h3 className="text-3xl text-stone-900 font-bold pb-5">Sign In to upload Files</h3>
            <div className="flex justify-evenly">
              <Link href="/login">
                <Button size="lg" variant="default">
                  SignIn
                </Button>
              </Link>
              <Link href="/signup">
                <Button size="lg" variant="default">
                  SignUp
                </Button>
              </Link>
            </div>
          </div>
        )}

        {session.data?.user && (
          <div className="text-center">
            <p>Explore Skyvault. To Upload files head over to your dashboard</p>
            <Button size="md" variant="default">
              <Link href="/dashboard">Go to Dashboard</Link>
            </Button>
          </div>
        )}
      </main>
    </>
  );
}
