import Head from 'next/head';

import styles from '@/styles/Home.module.css';
import { loginEndpoint, skyvaultApi } from 'lib/services/endpoint';

export default function Home() {
  return (
    <>
      <Head>
        <title>SkyVault</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link
          rel="preload"
          href="../lib/services/auth.service.tsx"
          as="fetch"
          crossOrigin="anonymous"
        ></link> */}
        <link rel="icon" href="../public/cloudversify.svg" />
      </Head>
      <main>Home</main>
    </>
  );
}
